name: word_nest
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.2  # for internet connection control
  http: ^1.3.0
  shared_preferences: ^2.4.0 
  cupertino_icons: ^1.0.8    
  json_annotation: ^4.9.0    
  flutter_bloc: ^8.0.0       
  flutter_card_swiper: ^7.0.2
  sqflite: ^2.4.1 
  path: ^1.9.0 
  loader_overlay: ^5.0.0
  logger: ^2.6.0
  custom_refresh_indicator: ^4.0.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_dismissible_tile: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0      
  json_serializable: ^6.9.0  
  build_runner: ^2.4.6       

flutter_native_splash:
  android: true
  ios: true
  image: assets/app_icon.png
  color: "#FFFFFF"

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: assets/app_icon.png
  image_path_ios: assets/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/app_icon.png

flutter:
  uses-material-design: true
  assets:
  - assets/
