name: word_nest
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
    # for internet connection control
  connectivity_plus: ^6.1.2
  http: ^1.3.0
  shared_preferences: ^2.4.0
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0 #for json to dart or exact opposite

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0 #for json to dart op exact opposite
  build_runner: ^2.4.6 #for json to dart or exact opposite

flutter:
  uses-material-design: true
  assets:
  - lib/assets/
